simpletickets/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import TicketList, TicketCreate, TicketDelete, TicketUpdate

from simpletickets.settings.ticketSettings import (ST_REST_API,
    API_BASE_URL
    )  # noqa

from .api.views import (UserTicketListCreate, UserTicketUpdateDelete,
    StaffTicketList, StaffTicketUpdate
    )

admin.autodiscover()

urlpatterns = [
    url(r'^list/$', TicketList.as_view(), name='ticketList'),
    url(r'^new-ticket/$', TicketCreate.as_view(), name='newTicket'),
    url(r'^edit-ticket-(?P<ST_id>[\d]*)/$',
        TicketUpdate.as_view(), name='TicketUpdate'
        ),
    url(r'^delete-ticket-(?P<ST_id>[\d]*)/$',
        TicketDelete.as_view(), name='TicketDelete'
        ),
    ]

if ST_REST_API:
    urlpatterns += [
        url(r'^{url}/list-create/$'.format(url=API_BASE_URL),
            UserTicketListCreate.as_view(),
            name='apiListCreate'
            ),
        url(r'^{url}/ticket-(?P<pk>[\d]+)-update-destroy/$'.format(
                url=API_BASE_URL
                ),
            UserTicketUpdateDelete.as_view(),
            name='updateDestroyCreate'
            ),
        url(r'^{url}/staff-list/$'.format(url=API_BASE_URL),
            StaffTicketList.as_view(),
            name='apiListCreate'
            ),
        url(r'^{url}/staff-ticket-(?P<pk>[\d]+)-update/$'.format(
                url=API_BASE_URL
                ),
            StaffTicketUpdate.as_view(),
            name='updateDestroyCreate'
            ),
        ]

simpletickets/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy as ugl
from django.conf import settings

from .settings import (ST_ATTACHMENTS, ST_DELTA_CLOSE,
    ST_TCKT_TYPE, ST_TCKT_SEVERITY, ST_TCKT_STATE,
    )
from .helpers import monitor, monitorfile, monitorfile_url

from .simpleemail.email_helper import EmailManager


def uploadAttachment(instance, filename):
    return os.path.join(ST_ATTACHMENTS, filename)


class TicketManager(models.Manager):
    def n_solved(self, user):
        return len(Ticket.objects.filter(state__gt=7, user=user))

    def n_total(self, user):
        return len(Ticket.objects.filter(user=user))

    def all(self):
        all_objects = super(TicketManager, self).all()

        # rewrite the all() method
        # so we can update files older than ST_DELTA_CLOSE to state 9
        now_minus_delta = timezone.now() - ST_DELTA_CLOSE
        state_8_delta = all_objects.filter(
            state=8,
            resolution_date__lt=now_minus_delta
            )
        state_8_delta.update(state=9)

        return all_objects


class Ticket(models.Model):
    objects = TicketManager()
    ticket_number = models.CharField(max_length=8, blank=True, null=True)

    user = models.ForeignKey(User,)
    staff = models.ForeignKey(User,
        limit_choices_to={'is_staff': True},
        related_name='usrStaff',
        blank=True, null=True,
        )

    ticket_type = models.IntegerField(default=2, choices=ST_TCKT_TYPE)
    severity = models.IntegerField(default=3, choices=ST_TCKT_SEVERITY)
    state = models.IntegerField(default=1, choices=ST_TCKT_STATE)

    description = models.TextField(ugl(u'Description'), default='...')
    attachment = models.FileField(upload_to=uploadAttachment,
        blank=True, null=True)

    resolution_text = models.TextField(ugl(u'Resolution text'), default='')

    creation_date = models.DateTimeField(_('Creation Date'),
        default=timezone.now)
    modification_date = models.DateTimeField(_('Last Modification Date'),
        blank=True, null=True)
    resolution_date = models.DateTimeField(_('Resolution date'),
        blank=True, null=True)

    resolution_delta = models.FloatField(_('delayed time in seconds'),
        blank=True, null=True)

    def mntrfile(self):
        return monitorfile_url(self)

    def resolucion_tag(self):
        return mark_safe(self.resolution_text)

    def humanized_delta(self):
        return self.resolution_date - self.creation_date

    def save(self, *args, **kwargs):
        self.modification_date = timezone.now()
        if self.id:
            header_msg = self.changesChecker(
                Ticket.objects.get(id=self.id),
                self
                )
        else:
            header_msg = _('{date} #### Ticket created ####\n').format(
                date=self.creation_date,
                )
        if self.state == 1:
            if self.staff:
                self.state = 2
        elif self.state > 7:
            self.resolution_date = timezone.now()
        if self.resolution_date:
            delta = self.resolution_date - self.creation_date
            self.resolution_delta = int(delta.total_seconds())
        super(Ticket, self).save(*args, **kwargs)
        monitor(monitorfile(self), header_msg)
        if not self.ticket_number:
            self.ticket_number = str(self.creation_date)[2:4] + (
                '00000{id}'.format(id=self.id)
                )[-6:]
            self.save()

    def _mailSender(self):
        context = ''
        if self.state == 9:
            context = {}
            subject = _(
                'Your ticket number {ticket_number} has been solved'
                ).format(ticket_number=self.ticket_number)
            body = _('We are glad we have solved your ticket number: '
                '{ticket_number}\n\n'
                'The resolution time was {resolution_delta}.\n\n'
                'You have {ST_DELTA_CLOSE} hours to reopen it, '
                'remember to carefully explain your reasons.\nThe Team'
                ).format(ticket_number=self.ticket_number,
                    resolution_delta=self.resolution_delta,
                    ST_DELTA_CLOSE=ST_DELTA_CLOSE
                    )
            email = self.user.email
            self.sendEmail(context, subject, body, email)
        if self.state == 2:
            context = {}
            subject = _(
                'Ticket {ticket_number} assigned.\n\nThe Team'
                ).format(ticket_number=self.ticket_number)
            body = _(
                'You have been assigned ticket number {ticket_number}.'
                '\n\nThe Team'
                ).format(ticket_number=self.ticket_number)
            email = self.staff.email
            self.sendEmail(context, subject, body, email)

    def changesChecker(self, original, actual):
        MONITORIZED = ['ticket_number', 'user', 'staff', 'ticket_type',
            'severity', 'state', 'description', 'resolution_text'
            ]
        msg = []
        for attribute in MONITORIZED:
            attr_ori = getattr(original, attribute)
            attr_act = getattr(actual, attribute)
            value = attr_act
            if attribute in ['ticket_type', 'severity', 'state']:
                value = getattr(actual, 'get_{attribute}_display'.format(
                    attribute=attribute)
                    )()
            if not attr_ori == attr_act and (attr_ori or attr_act):
                msg.append(
                    '[{attrname}: {attrvalue}]'.format(
                        attrname=attribute.upper(),
                        attrvalue=value,
                        )
                    )
        if msg:
            msg = ' | '.join(msg) + '\n'
        else:
            msg = 'No changes!\n'
        return msg

    def sendEmail(self, context, subject, body, email):
        EmailManager(context,
            subject=subject,
            body=body,
            from_email=settings.EMAIL_HOST_USER,
            to=self.user.email,
            bcc=email,
            connection=None,
            attachments=None,
            headers=None,
            alternatives=None,
            cc=None,
            reply_to=None
            )

    def __unicode__(self):
        return u'{ticket_number} {user}'.format(
            ticket_number=self.ticket_number,
            user=self.user,
            )

    class Meta(object):
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')
        ordering = ('state', 'severity', 'creation_date')

simpletickets/templates/simpletickets/ticket_confirm_delete.html
{% extends 'simpletickets/tickets_base.html' %}
{% block tickets %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                       type="button" value="Cancel"
                       onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>
{% endblock tickets %}

simpletickets/templates/simpletickets/ticket_form.html
{% extends 'simpletickets/tickets_base.html' %}
{% load bootstrap %}
{% block tickets %}
{% if request.user.is_staff %}
<h3>{{ form.instance.description }}</h3>

{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form|bootstrap }}
    Fields marked with * are mandatory
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock tickets %}

simpletickets/templates/simpletickets/ticket_list.html
{% extends 'simpletickets/tickets_base.html' %}
{% block tickets %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Ticket list</h3>
    </div>
    <div class="table-responsive">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>ticket</th>
                    <th style="min-width:100px">actions</th>
                    <th>
                        {% if user.is_staff %}
                            staff
                        {% else %}
                            state
                        {% endif %}
                    </th>
                    <th>severity</th>
                    <th>date</th>
                    <th>description</th>
                </tr>
            </thead>
            <tbody>
            {% for ticket in object_list %}
                <tr class="{% ifequal ticket.state 1 %}danger{% endifequal %}{% ifequal ticket.state 2 %}warning{% endifequal %}{% if ticket.state > 2 and ticket.state < 8 %}info{% endif %}{% ifequal ticket.state 8 %}success{% endifequal %}{% ifequal ticket.state 9 %}active{% endifequal %}">
                    <td>{{ ticket.ticket_number }}</td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="ticket actions">
                            {% if request.user.is_staff %}
                                <button disabled="disabled" type="button" class="btn btn-default" title="can't delete">X</button>
                                {% if ticket.state < 8  %}
                                    <a href="{% url 'TicketUpdate' ticket.id %}" role="button" class="btn btn-primary" title="modify">M</a>
                                {% else %}
                                    <button disabled="disabled" type="button" class="btn btn-default" title="can't modify">M</button>
                                {% endif %}
                            {% else %}
                                {% ifequal ticket.state 1 %}
                                    <a href="{% url 'TicketDelete' ticket.id %}" role="button" class="btn btn-danger" title="delete">X</a>
                                    <a href="{% url 'TicketUpdate' ticket.id %}" role="button" class="btn btn-primary" title="modify">M</a>
                                {% else %}
                                    <button disabled="disabled" type="button" class="btn btn-default" title="can't delete">X</button>
                                    {% ifequal ticket.state 8 %}
                                        <a href="{% url 'TicketUpdate' ticket.id %}" role="button" class="btn btn-primary" title="modify">M</a>
                                    {% else %}
                                        <button disabled="disabled" type="button" class="btn btn-default" title="can't modify">M</button>
                                    {% endifequal %}
                                {% endifequal %}
                            {% endif %}
                            {% if ticket.attachment %}
                                <button type="button" class="btn btn-warning" title="attachment"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></button>
                            {% else %}
                                <button disabled="disabled" type="button" class="btn btn-default" title="no attachment"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></button>
                            {% endif %}
                            {% if ST_MNTR %}
                                <a href={{ ticket.mntrfile }} role="button" class="btn btn-primary" title="progress file"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></a>
                            {% endif %}
                        </div>
                    </td>
                    <td>
                        {% if user.is_staff %}
                            {{ ticket.staff }}
                        {% else %}
                            {{ ticket.get_state_display }}
                        {% endif %}
                    </td>
                    <td>
                        {% if ticket.severity > 2 %}
                            {% ifequal ticket.severity 9 %}
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
                            {% endifequal %}
                        {% endif %}
                        {% ifequal ticket.severity 2 %}<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>{% endifequal %}
                        {% ifequal ticket.severity 1 %}<span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>{% endifequal %}
                        {{ ticket.get_severity_display }}
                    </td>
                    <td>
                        {% if ticket.state > 7 %}
                            delayed for {{ ticket.humanized_delta }}
                        {% else %}
                            {{ ticket.creation_date }}</td>
                        {% endif %}
                    <td>
                        {% if ticket.state > 2 %}
                            {% if  ticket.state < 9 %}
                                {{ ticket.resolution_text }}
                            {% endif %}
                        {% else %}
                            {{ ticket.description }}</td>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            {% if not request.user.is_staff %}
            <tr><td>new ticket</td><td><div class="btn-group btn-group-xs" role="group"><a href="{% url 'newTicket' %}" role="button" class="btn btn-success" title="create">+</a></div></td><td></td><td></td><td></td><td></td></tr>
            {% endif %}
            </tbody>
        </table>
        <div class="panel-footer">
            <span>Leyend:</span>
            <span class="text-danger">new</span> |
            <span class="text-warning">asigned</span> |
            <span class="text-info">delayed</span> |
            <span class="text-success">solved</span> |
            <span class="text-active">closed</span> |
        </div>
    </div>
</div>
{% endblock tickets %}

simpletickets/templates/simpletickets/tickets_base.html
{% extends base_template %}
{% block simpletickets %}
    <div class="container-fluid">
        {% if ST_SETT_MAIN_TASKBAR %}
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">Ticket system</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <button href="{% url 'ticketList' %}" type="button" class="btn btn-info navbar-btn">Tickets</button>
                                    <button href="{% url 'newTicket' %}" type="button" class="btn btn-success navbar-btn">New ticket</button>
                                </ul>
                            </div>
                        </div>{# div .container-fluid #}
                    </nav>{# nav .navbar #}
                </div>
            </div>{# div .rov #}
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                {% block tickets %}
                {% endblock tickets %}
            </div>
        </div>{# div .rov #}
        <div class="row">
            {% if statistic_times %}
                <div class="col-xl-4 col-md-6 col-xs-12">
                    <div class="col-md-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Resolution times</h3>
                            </div>
                            <div class="panel-body">
                                <p>Fastest: {{ fastest }}</p>
                                <p>Media: {{ media }}</p>
                            </div>
                        </div>
                    </div>
                </div>{# div .col-xl-4 col-md-6 col-xs-12 #}
            {% endif %}
            {% if stt_numb %}
                <div class="col-xl-4 col-md-6 col-xs-12">
                    <div class="col-md-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Tickets statistics</h3>
                            </div>{# div .panel-heading #}
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-xl-6 col-md-6 col-xs-12"><p>Solved vs pending tickets </p></div>
                                    <div class="col-xl-6 col-md-6 col-xs-12">
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ porc_solved }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ porc_solved }}%">
                                            {{ porc_solved }}%
                                            </div>
                                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="{{ porc_pending }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ porc_pending }}%">
                                            {{ porc_pending }}%
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>{# div .panel-body #}
                        </div>
                    </div>
                </div>{# div .col-xl-4 col-md-6 col-xs-12 #}
            {% endif %}
        </div>{# div .row #}
    </div>
{% endblock simpletickets %}